In [1]:
import pandas as pd

In [2]:
players_all = pd.read_csv("all_players.csv")

In [3]:
players_all.head()

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup,league,season
0,227,Robert Lewandowski,29,2467,41,32.077339,7,4.815550,135,32,4,0,F S,Bayern Munich,33,25.257350,31.740188,5.689343,Bundesliga,2020-2021
1,6170,André Silva,32,2787,28,25.599132,5,5.467086,114,31,1,0,F,Eintracht Frankfurt,21,20.294786,26.746589,4.096429,Bundesliga,2020-2021
2,8260,Erling Haaland,28,2416,27,23.598484,6,4.035448,92,27,2,0,F S,Borussia Dortmund,25,20.567369,27.197287,5.896189,Bundesliga,2020-2021
3,956,Andrej Kramaric,28,2386,20,15.525600,5,4.072423,95,38,2,0,F M S,Hoffenheim,15,11.736730,18.057688,5.372287,Bundesliga,2020-2021
4,7052,Wout Weghorst,34,2954,20,18.310400,8,5.427310,93,45,3,0,F S,Wolfsburg,18,16.037062,24.294329,5.954853,Bundesliga,2020-2021

In [4]:
stats_cols = [
    "goals", "xG", "assists", "xA", "shots",
    "key_passes", "yellow_cards", "red_cards",
    "npg", "npxG", "xGChain", "xGBuildup"
]

In [5]:
MIN_MINUTES = 900

players_all = players_all[players_all["time"] >= MIN_MINUTES].copy()

In [6]:
for col in stats_cols:
    players_all[f"{col}_90"] = players_all[col] / players_all["time"] * 90

In [7]:
players_all.drop(columns=stats_cols, inplace=True)

In [8]:
players_all.shape

(8063, 20)

In [9]:
players_all.head()

,id,player_name,games,time,position,team_title,league,season,goals_90,xG_90,assists_90,xA_90,shots_90,key_passes_90,yellow_cards_90,red_cards_90,npg_90,npxG_90,xGChain_90,xGBuildup_90
0,227,Robert Lewandowski,29,2467,F S,Bayern Munich,Bundesliga,2020-2021,1.495744,1.170231,0.255371,0.175679,4.925010,1.167410,0.145926,0.0,1.203891,0.921427,1.157931,0.207556
1,6170,André Silva,32,2787,F,Eintracht Frankfurt,Bundesliga,2020-2021,0.904198,0.826667,0.161464,0.176547,3.681378,1.001076,0.032293,0.0,0.678149,0.655375,0.863722,0.132285
2,8260,Erling Haaland,28,2416,F S,Borussia Dortmund,Bundesliga,2020-2021,1.005795,0.879083,0.223510,0.150327,3.427152,1.005795,0.074503,0.0,0.931291,0.766169,1.013144,0.219643
3,956,Andrej Kramaric,28,2386,F M S,Hoffenheim,Bundesliga,2020-2021,0.754401,0.585626,0.188600,0.153612,3.583403,1.433361,0.075440,0.0,0.565801,0.442710,0.681137,0.202643
4,7052,Wout Weghorst,34,2954,F S,Wolfsburg,Bundesliga,2020-2021,0.609343,0.557866,0.243737,0.165355,2.833446,1.371022,0.091401,0.0,0.548409,0.488604,0.740179,0.181427

In [23]:
players_all.to_csv("all_players_normalized.csv", index=False)